(base) C:\Users\ezimm\OneDrive\Documents\Documents44-671\streaming-02-multiple-processes>C:/Users/ezimm/miniconda3/python.exe c:/Users/ezimm/OneDrive/Documents/Documents44-671/streaming-02-multiple-processes/multiple_processes.py


STARTING UP.............................
It's 2023-01-22 at 03:04 PM

This file is running on:    nt Windows 10
The Python version is:      3.9.12

The Python interpreter is at:
 C:\Users\ezimm\miniconda3\python.exe


DELETED tabble pets.
CREATED table pets.

P2 getting ready to insert Cooper the Rabbit.
P1 getting ready to insert Ace the Dog.
P3 getting ready to insert Emma the Rabbit.
P3 ADDED Emma the Rabbit.
P2 ADDED Cooper the Rabbit.
P3 getting ready to insert Felix the Cat.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\ezimm\miniconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\ezimm\miniconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\ezimm\OneDrive\Documents\Documents44-671\streaming-02-multiple-processes\multiple_processes.py", line 102, in process_one
    insert_pet("P1","Ace", "Dog")
  File "c:\Users\ezimm\OneDrive\Documents\Documents44-671\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked
P2 getting ready to insert Dufus the Dog.
P2 ADDED Dufus the Dog.
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\ezimm\miniconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\ezimm\miniconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\ezimm\OneDrive\Documents\Documents44-671\streaming-02-multiple-processes\multiple_processes.py", line 111, in process_three
    insert_pet("P3","Felix", "Cat")
  File "c:\Users\ezimm\OneDrive\Documents\Documents44-671\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked
